import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Footer } from '../components/Footer'
import { HomeLayer } from '../components/HomeLayer'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Project Alexandria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='App'>
          <div className='App-header'>
            <HomeLayer />
          </div>
        </div>

      </main>

      <Footer />
    </div>
  )
}

export default Home
